version: "2"
run:
  timeout: "5m"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.17"
  relative-path-mode: wd
linters:
  
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - gocognit
    - goconst
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - gosec
          - noctx
          - unparam
        path: _test\.go
      - linters:
          - gosec
        path: fixtures.go
      - path: (.+)\.go$
        text: composite literal uses unkeyed fields
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - examples$
