openapi: 3.0.3
info:
  title: Sumni Finance API
  description: API for managing finance operations including fund providers
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /v1/fund-provider:
    post:
      summary: Create a new fund provider
      description: Creates a new fund provider with an initial balance and currency
      operationId: createFundProvider
      tags:
        - Fund Provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFundProviderRequest"
      responses:
        "201":
          description: Fund provider created successfully
        "400":
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /v1/wallet:
    post:
      summary: Create a new wallet
      description: Creates a new wallet with initial fund provider allocations
      operationId: createWallet
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWalletRequest"
      responses:
        "201":
          description: Wallet created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateWalletResponse"
        "400":
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    CreateFundProviderRequest:
      type: object
      required:
        - balance
        - currency
      properties:
        balance:
          type: integer
          format: int64
          description: Initial balance for the fund provider
          example: 1000000
          minimum: 0
        currency:
          type: string
          description: Currency code (e.g., USD, VND, KRW)
          example: "USD"
          pattern: "^[A-Z]{3}$"
          minLength: 3
          maxLength: 3

    CreateWalletRequest:
      type: object
      required:
        - currency
        - allocations
      properties:
        currency:
          type: string
          description: Currency code (e.g., USD, VND, KRW)
          example: "VND"
          pattern: "^[a-zA-Z]{3}$"
          minLength: 3
          maxLength: 3
        allocations:
          type: array
          description: List of fund provider allocations
          minItems: 1
          items:
            $ref: "#/components/schemas/ProviderAllocation"

    ProviderAllocation:
      type: object
      required:
        - providerID
        - allocated
      properties:
        providerID:
          type: string
          format: uuid
          description: Fund provider unique identifier
          example: "019c46dc-d55a-71d0-a542-b56cd41440ae"
        allocated:
          type: integer
          format: int64
          description: Amount allocated from this provider
          example: 1000000
          minimum: 1

    CreateWalletResponse:
      type: object
      properties:
        request_id:
          type: string
          description: Request identifier for tracking
          example: "abc123xyz"

    ErrorResponse:
      type: object
      required:
        - request_id
        - error
      properties:
        request_id:
          type: string
          description: Request identifier for tracking
          example: "abc123xyz"
        error:
          type: object
          required:
            - slug
            - message
          properties:
            slug:
              type: string
              description: Error slug identifier
              example: "invalid-currency"
            message:
              type: string
              description: Human-readable error message
              example: "Currency code must be 3 uppercase letters"
