// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

// CreateFundProviderRequest defines model for CreateFundProviderRequest.
type CreateFundProviderRequest struct {
	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`

	// InitBalance Initial balance for the fund provider
	InitBalance int64 `json:"initBalance"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`
}

// CreateWalletResponse defines model for CreateWalletResponse.
type CreateWalletResponse struct {
	// RequestId Request identifier for tracking
	RequestId *string `json:"request_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Message Human-readable error message
		Message string `json:"message"`

		// Slug Error slug identifier
		Slug string `json:"slug"`
	} `json:"error"`

	// RequestId Request identifier for tracking
	RequestId string `json:"request_id"`
}

// CreateFundProviderJSONRequestBody defines body for CreateFundProvider for application/json ContentType.
type CreateFundProviderJSONRequestBody = CreateFundProviderRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest
