// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateFundProviderRequest defines model for CreateFundProviderRequest.
type CreateFundProviderRequest struct {
	// Balance Initial balance for the fund provider
	Balance int64 `json:"balance"`

	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	// Allocations List of fund provider allocations
	Allocations []ProviderAllocation `json:"allocations"`

	// Currency Currency code (e.g., USD, VND, KRW)
	Currency string `json:"currency"`
}

// CreateWalletResponse defines model for CreateWalletResponse.
type CreateWalletResponse struct {
	// RequestId Request identifier for tracking
	RequestId *string `json:"request_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RequestId Request identifier for tracking
	RequestId *string `json:"request_id,omitempty"`

	// Slug Error slug identifier
	Slug *string `json:"slug,omitempty"`
}

// ProviderAllocation defines model for ProviderAllocation.
type ProviderAllocation struct {
	// Allocated Amount allocated from this provider
	Allocated int64 `json:"allocated"`

	// ProviderID Fund provider unique identifier
	ProviderID openapi_types.UUID `json:"providerID"`
}

// CreateFundProviderJSONRequestBody defines body for CreateFundProvider for application/json ContentType.
type CreateFundProviderJSONRequestBody = CreateFundProviderRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest
