// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_sources.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetSource = `-- name: CreateAssetSource :exec
INSERT INTO finance.asset_sources (
    id, 
    owner_id, 
    balance, 
    source_type, 
    currency_code, 
    bank_name, 
    account_number,
    office_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAssetSourceParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Balance       int64
	SourceType    string
	CurrencyCode  string
	BankName      pgtype.Text
	AccountNumber pgtype.Text
	OfficeID      uuid.UUID
}

func (q *Queries) CreateAssetSource(ctx context.Context, arg CreateAssetSourceParams) error {
	_, err := q.db.Exec(ctx, createAssetSource,
		arg.ID,
		arg.OwnerID,
		arg.Balance,
		arg.SourceType,
		arg.CurrencyCode,
		arg.BankName,
		arg.AccountNumber,
		arg.OfficeID,
	)
	return err
}
