// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_sources.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetsource = `-- name: CreateAssetsource :exec
INSERT INTO finance.asset_sources (
    id, 
    owner_id, 
    balance, 
    source_type, 
    currency_code, 
    bank_name, 
    account_number
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAssetsourceParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Balance       int64
	SourceType    string
	CurrencyCode  string
	BankName      pgtype.Text
	AccountNumber pgtype.Text
}

func (q *Queries) CreateAssetsource(ctx context.Context, arg CreateAssetsourceParams) error {
	_, err := q.db.Exec(ctx, createAssetsource,
		arg.ID,
		arg.OwnerID,
		arg.Balance,
		arg.SourceType,
		arg.CurrencyCode,
		arg.BankName,
		arg.AccountNumber,
	)
	return err
}

const listAssetSources = `-- name: ListAssetSources :many
SELECT id, owner_id, balance, source_type, currency_code, bank_name, account_number 
FROM finance.asset_sources
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAssetSourcesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAssetSources(ctx context.Context, arg ListAssetSourcesParams) ([]FinanceAssetSource, error) {
	rows, err := q.db.Query(ctx, listAssetSources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceAssetSource
	for rows.Next() {
		var i FinanceAssetSource
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Balance,
			&i.SourceType,
			&i.CurrencyCode,
			&i.BankName,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
