// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreatFundProviderAllocation implements pgx.CopyFromSource.
type iteratorForCreatFundProviderAllocation struct {
	rows                 []CreatFundProviderAllocationParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatFundProviderAllocation) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatFundProviderAllocation) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FundProviderID,
		r.rows[0].WalletID,
		r.rows[0].AllocatedAmount,
	}, nil
}

func (r iteratorForCreatFundProviderAllocation) Err() error {
	return nil
}

func (q *Queries) CreatFundProviderAllocation(ctx context.Context, arg []CreatFundProviderAllocationParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"finance", "fund_provider_allocation"}, []string{"fund_provider_id", "wallet_id", "allocated_amount"}, &iteratorForCreatFundProviderAllocation{rows: arg})
}
