// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateWalletAssetSourceAssociateBatch implements pgx.CopyFromSource.
type iteratorForCreateWalletAssetSourceAssociateBatch struct {
	rows                 []CreateWalletAssetSourceAssociateBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWalletAssetSourceAssociateBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWalletAssetSourceAssociateBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AssetSourceID,
		r.rows[0].WalletID,
	}, nil
}

func (r iteratorForCreateWalletAssetSourceAssociateBatch) Err() error {
	return nil
}

func (q *Queries) CreateWalletAssetSourceAssociateBatch(ctx context.Context, arg []CreateWalletAssetSourceAssociateBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"finance", "assetsource_wallet"}, []string{"asset_source_id", "wallet_id"}, &iteratorForCreateWalletAssetSourceAssociateBatch{rows: arg})
}
