// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateWalletsAllocationBatch implements pgx.CopyFromSource.
type iteratorForCreateWalletsAllocationBatch struct {
	rows                 []CreateWalletsAllocationBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWalletsAllocationBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWalletsAllocationBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AssetSourceID,
		r.rows[0].WalletID,
		r.rows[0].Amount,
	}, nil
}

func (r iteratorForCreateWalletsAllocationBatch) Err() error {
	return nil
}

func (q *Queries) CreateWalletsAllocationBatch(ctx context.Context, arg []CreateWalletsAllocationBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"finance", "wallets_allocation"}, []string{"asset_source_id", "wallet_id", "amount"}, &iteratorForCreateWalletsAllocationBatch{rows: arg})
}
