// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fund_provider.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createFundProvider = `-- name: CreateFundProvider :exec
INSERT INTO finance.fund_providers (
    id,
    balance,
    currency,
    version
) VALUES(
    $1, -- id
    $2, -- balance
    $3, -- currency
    $4  -- version
)
`

type CreateFundProviderParams struct {
	ID       uuid.UUID
	Balance  int64
	Currency string
	Version  int32
}

func (q *Queries) CreateFundProvider(ctx context.Context, arg CreateFundProviderParams) error {
	_, err := q.db.Exec(ctx, createFundProvider,
		arg.ID,
		arg.Balance,
		arg.Currency,
		arg.Version,
	)
	return err
}

const getFundProviderByID = `-- name: GetFundProviderByID :one
SELECT 
    id,
    balance,
    currency,
    version
FROM finance.fund_providers
WHERE id = $1
`

func (q *Queries) GetFundProviderByID(ctx context.Context, id uuid.UUID) (FinanceFundProvider, error) {
	row := q.db.QueryRow(ctx, getFundProviderByID, id)
	var i FinanceFundProvider
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.Version,
	)
	return i, err
}
