// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fund_provider.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createFundProvider = `-- name: CreateFundProvider :exec
INSERT INTO finance.fund_providers (
    id,
    balance,
    currency,
    version
) VALUES(
    $1, -- id
    $2, -- balance
    $3, -- currency
    $4  -- version
)
`

type CreateFundProviderParams struct {
	ID       uuid.UUID
	Balance  int64
	Currency string
	Version  int32
}

func (q *Queries) CreateFundProvider(ctx context.Context, arg CreateFundProviderParams) error {
	_, err := q.db.Exec(ctx, createFundProvider,
		arg.ID,
		arg.Balance,
		arg.Currency,
		arg.Version,
	)
	return err
}

const getFundProviderByID = `-- name: GetFundProviderByID :one
SELECT 
    id,
    balance,
    currency,
    version,
    fp.balance - COALESCE(SUM(fpa.allocated_amount), 0) as available_amount
FROM finance.fund_providers fp
    LEFT JOIN finance.fund_provider_allocation fpa
        ON fp.id = fpa.fund_provider_id
WHERE id = $1
GROUP BY fp.id
`

type GetFundProviderByIDRow struct {
	ID              uuid.UUID
	Balance         int64
	Currency        string
	Version         int32
	AvailableAmount int32
}

func (q *Queries) GetFundProviderByID(ctx context.Context, id uuid.UUID) (GetFundProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getFundProviderByID, id)
	var i GetFundProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.Version,
		&i.AvailableAmount,
	)
	return i, err
}
