// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ledger.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertTransactionRecordsParams struct {
	ID                  uuid.UUID `db:"id"`
	TransactionNo       *string   `db:"transaction_no"`
	TransactionType     string    `db:"transaction_type"`
	Amount              int64     `db:"amount"`
	WalletBalance       int64     `db:"wallet_balance"`
	WalletID            uuid.UUID `db:"wallet_id"`
	FpID                uuid.UUID `db:"fp_id"`
	FpBalance           int64     `db:"fp_balance"`
	AccountingPeriodsID uuid.UUID `db:"accounting_periods_id"`
}

const createAccountingPeriod = `-- name: CreateAccountingPeriod :exec
INSERT INTO finance.accounting_periods (
    id,
    year_month,
    start_date,
    interval,
    end_time,
    wallet_opening_balance,
    total_debit,
    total_credit,
    wallet_closing_balance,
    version,
    wallet_id,
    status
) VALUES (
    $1, -- id
    $2, -- year_month
    $3, -- start_date
    $4, -- interval
    $5, -- end_time
    $6, -- wallet_opening_balance
    $7, -- total_debit
    $8, -- total_credit
    $9, -- wallet_closing_balance
    $10, -- version
    $11, -- wallet_id
    $12 -- status
)
`

type CreateAccountingPeriodParams struct {
	ID                   uuid.UUID `db:"id"`
	YearMonth            string    `db:"year_month"`
	StartDate            int32     `db:"start_date"`
	Interval             int32     `db:"interval"`
	EndTime              time.Time `db:"end_time"`
	WalletOpeningBalance int64     `db:"wallet_opening_balance"`
	TotalDebit           int64     `db:"total_debit"`
	TotalCredit          int64     `db:"total_credit"`
	WalletClosingBalance int64     `db:"wallet_closing_balance"`
	Version              int32     `db:"version"`
	WalletID             uuid.UUID `db:"wallet_id"`
	Status               string    `db:"status"`
}

func (q *Queries) CreateAccountingPeriod(ctx context.Context, arg CreateAccountingPeriodParams) error {
	_, err := q.db.Exec(ctx, createAccountingPeriod,
		arg.ID,
		arg.YearMonth,
		arg.StartDate,
		arg.Interval,
		arg.EndTime,
		arg.WalletOpeningBalance,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.WalletClosingBalance,
		arg.Version,
		arg.WalletID,
		arg.Status,
	)
	return err
}

const getAccountingPeriodsByYearMonthAndWalletID = `-- name: GetAccountingPeriodsByYearMonthAndWalletID :one
SELECT
    id,
    year_month,
    start_date,
    interval,
    end_time,
    wallet_opening_balance,
    total_debit,
    total_credit,
    wallet_closing_balance,
    status,
    version
FROM
    finance.accounting_periods
WHERE wallet_id = $1 
    AND year_month = $2
`

type GetAccountingPeriodsByYearMonthAndWalletIDParams struct {
	WalletID  uuid.UUID `db:"wallet_id"`
	YearMonth string    `db:"year_month"`
}

type GetAccountingPeriodsByYearMonthAndWalletIDRow struct {
	ID                   uuid.UUID `db:"id"`
	YearMonth            string    `db:"year_month"`
	StartDate            int32     `db:"start_date"`
	Interval             int32     `db:"interval"`
	EndTime              time.Time `db:"end_time"`
	WalletOpeningBalance int64     `db:"wallet_opening_balance"`
	TotalDebit           int64     `db:"total_debit"`
	TotalCredit          int64     `db:"total_credit"`
	WalletClosingBalance int64     `db:"wallet_closing_balance"`
	Status               string    `db:"status"`
	Version              int32     `db:"version"`
}

func (q *Queries) GetAccountingPeriodsByYearMonthAndWalletID(ctx context.Context, arg GetAccountingPeriodsByYearMonthAndWalletIDParams) (GetAccountingPeriodsByYearMonthAndWalletIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountingPeriodsByYearMonthAndWalletID, arg.WalletID, arg.YearMonth)
	var i GetAccountingPeriodsByYearMonthAndWalletIDRow
	err := row.Scan(
		&i.ID,
		&i.YearMonth,
		&i.StartDate,
		&i.Interval,
		&i.EndTime,
		&i.WalletOpeningBalance,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.WalletClosingBalance,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const getWalletWithAccountingPeriod = `-- name: GetWalletWithAccountingPeriod :one
SELECT
    w.id             AS wallet_id,
    w.name           AS wallet_name,
    w.balance        AS wallet_balance,
    w.currency       AS wallet_currency,
    w.version        AS wallet_version,
    ap.id            AS period_id,
    ap.year_month    AS period_year_month,
    ap.start_date    AS period_start_date,
    ap.interval      AS period_interval,
    ap.end_time      AS period_end_time,
    ap.wallet_opening_balance,
    ap.total_debit,
    ap.total_credit,
    ap.wallet_closing_balance,
    ap.status        AS period_status,
    ap.version       AS period_version
FROM finance.wallets w
LEFT JOIN finance.accounting_periods ap
    ON ap.wallet_id = w.id
    AND ap.year_month = $2
WHERE w.id = $1
`

type GetWalletWithAccountingPeriodParams struct {
	ID        uuid.UUID `db:"id"`
	YearMonth string    `db:"year_month"`
}

type GetWalletWithAccountingPeriodRow struct {
	WalletID             uuid.UUID        `db:"wallet_id"`
	WalletName           string           `db:"wallet_name"`
	WalletBalance        int64            `db:"wallet_balance"`
	WalletCurrency       string           `db:"wallet_currency"`
	WalletVersion        int32            `db:"wallet_version"`
	PeriodID             *uuid.UUID       `db:"period_id"`
	PeriodYearMonth      *string          `db:"period_year_month"`
	PeriodStartDate      *int32           `db:"period_start_date"`
	PeriodInterval       *int32           `db:"period_interval"`
	PeriodEndTime        pgtype.Timestamp `db:"period_end_time"`
	WalletOpeningBalance *int64           `db:"wallet_opening_balance"`
	TotalDebit           *int64           `db:"total_debit"`
	TotalCredit          *int64           `db:"total_credit"`
	WalletClosingBalance *int64           `db:"wallet_closing_balance"`
	PeriodStatus         *string          `db:"period_status"`
	PeriodVersion        *int32           `db:"period_version"`
}

func (q *Queries) GetWalletWithAccountingPeriod(ctx context.Context, arg GetWalletWithAccountingPeriodParams) (GetWalletWithAccountingPeriodRow, error) {
	row := q.db.QueryRow(ctx, getWalletWithAccountingPeriod, arg.ID, arg.YearMonth)
	var i GetWalletWithAccountingPeriodRow
	err := row.Scan(
		&i.WalletID,
		&i.WalletName,
		&i.WalletBalance,
		&i.WalletCurrency,
		&i.WalletVersion,
		&i.PeriodID,
		&i.PeriodYearMonth,
		&i.PeriodStartDate,
		&i.PeriodInterval,
		&i.PeriodEndTime,
		&i.WalletOpeningBalance,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.WalletClosingBalance,
		&i.PeriodStatus,
		&i.PeriodVersion,
	)
	return i, err
}

const updateAccountingPeriod = `-- name: UpdateAccountingPeriod :execrows
UPDATE finance.accounting_periods ap
SET
    total_debit = $1,
    total_credit = $2,
    wallet_closing_balance = $3,
    status = $4,
    version = version + 1
WHERE ap.id = $5
    AND ap.version = $6
`

type UpdateAccountingPeriodParams struct {
	TotalDebit     int64     `db:"total_debit"`
	TotalCredit    int64     `db:"total_credit"`
	ClosingBalance int64     `db:"closing_balance"`
	Status         string    `db:"status"`
	ID             uuid.UUID `db:"id"`
	Version        int32     `db:"version"`
}

func (q *Queries) UpdateAccountingPeriod(ctx context.Context, arg UpdateAccountingPeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountingPeriod,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.ClosingBalance,
		arg.Status,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
