// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
)

type FinanceFundProvider struct {
	ID              uuid.UUID
	Balance         int64
	Currency        string
	AvailableAmount int64
	Version         int32
}

type FinanceFundProviderAllocation struct {
	FundProviderID  uuid.UUID
	WalletID        uuid.UUID
	AllocatedAmount int64
}

type FinanceWallet struct {
	ID       uuid.UUID
	Balance  int64
	Currency string
	Version  int32
}
