// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FinanceAssetSource struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	AssetsourceName string
	Balance         int64
	SourceType      string
	CurrencyCode    string
	OfficeID        uuid.UUID
	BankName        pgtype.Text
	AccountNumber   pgtype.Text
}

type FinanceWallet struct {
	ID           uuid.UUID
	WalletName   string
	CurrencyCode string
	Balance      int64
	IsStrictMode bool
	OfficeID     uuid.UUID
}

type FinanceWalletsAllocation struct {
	AssetSourceID uuid.UUID
	WalletID      uuid.UUID
	Amount        int64
}
