// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FinanceAssetSource struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Balance       int64
	SourceType    string
	CurrencyCode  string
	BankName      pgtype.Text
	AccountNumber pgtype.Text
}

type FinanceAssetsourceWallet struct {
	AssetsourceID uuid.UUID
	WalletID      uuid.UUID
}

type FinanceWallet struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	Name         string
	CurrencyCode string
	IsStrictMode pgtype.Bool
}
