// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wallet.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO finance.wallets (
    id,
    name,
    balance,
    currency,
    version
) VALUES (
    $1, -- id
    $2, -- name
    $3, -- balance
    $4, -- currency
    $5 -- version
)
`

type CreateWalletParams struct {
	ID       uuid.UUID
	Name     string
	Balance  int64
	Currency string
	Version  int32
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.Exec(ctx, createWallet,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.Currency,
		arg.Version,
	)
	return err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT 
    id,
    name,
    balance,
    currency,
    version
FROM finance.wallets
WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id uuid.UUID) (FinanceWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i FinanceWallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.Version,
	)
	return i, err
}

const updateWalletPartial = `-- name: UpdateWalletPartial :execrows
UPDATE finance.wallets
SET
    name = COALESCE($1, name),
    balance  = COALESCE($2, balance),
    currency = COALESCE($3, currency),
    version  = version + 1
WHERE id = $4
  AND version = $5
`

type UpdateWalletPartialParams struct {
	Name     pgtype.Text
	Balance  pgtype.Int8
	Currency pgtype.Text
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) UpdateWalletPartial(ctx context.Context, arg UpdateWalletPartialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWalletPartial,
		arg.Name,
		arg.Balance,
		arg.Currency,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFundProviderAllocation = `-- name: UpsertFundProviderAllocation :exec
INSERT INTO finance.fund_provider_allocation (
    fund_provider_id,
    wallet_id,
    allocated_amount
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (fund_provider_id, wallet_id)
DO UPDATE
SET allocated_amount = EXCLUDED.allocated_amount
`

type UpsertFundProviderAllocationParams struct {
	FundProviderID  uuid.UUID
	WalletID        uuid.UUID
	AllocatedAmount int64
}

func (q *Queries) UpsertFundProviderAllocation(ctx context.Context, arg UpsertFundProviderAllocationParams) error {
	_, err := q.db.Exec(ctx, upsertFundProviderAllocation, arg.FundProviderID, arg.WalletID, arg.AllocatedAmount)
	return err
}
