// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"sumni-finance-backend/internal/finance/app/query"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletReadModel creates a new instance of MockWalletReadModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletReadModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletReadModel {
	mock := &MockWalletReadModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletReadModel is an autogenerated mock type for the WalletReadModel type
type MockWalletReadModel struct {
	mock.Mock
}

type MockWalletReadModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletReadModel) EXPECT() *MockWalletReadModel_Expecter {
	return &MockWalletReadModel_Expecter{mock: &_m.Mock}
}

// GetAllWalletsWithAllocations provides a mock function for the type MockWalletReadModel
func (_mock *MockWalletReadModel) GetAllWalletsWithAllocations(ctx context.Context, officeID uuid.UUID) ([]query.Wallet, error) {
	ret := _mock.Called(ctx, officeID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWalletsWithAllocations")
	}

	var r0 []query.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]query.Wallet, error)); ok {
		return returnFunc(ctx, officeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []query.Wallet); ok {
		r0 = returnFunc(ctx, officeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]query.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, officeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletReadModel_GetAllWalletsWithAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWalletsWithAllocations'
type MockWalletReadModel_GetAllWalletsWithAllocations_Call struct {
	*mock.Call
}

// GetAllWalletsWithAllocations is a helper method to define mock.On call
//   - ctx context.Context
//   - officeID uuid.UUID
func (_e *MockWalletReadModel_Expecter) GetAllWalletsWithAllocations(ctx interface{}, officeID interface{}) *MockWalletReadModel_GetAllWalletsWithAllocations_Call {
	return &MockWalletReadModel_GetAllWalletsWithAllocations_Call{Call: _e.mock.On("GetAllWalletsWithAllocations", ctx, officeID)}
}

func (_c *MockWalletReadModel_GetAllWalletsWithAllocations_Call) Run(run func(ctx context.Context, officeID uuid.UUID)) *MockWalletReadModel_GetAllWalletsWithAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletReadModel_GetAllWalletsWithAllocations_Call) Return(wallets []query.Wallet, err error) *MockWalletReadModel_GetAllWalletsWithAllocations_Call {
	_c.Call.Return(wallets, err)
	return _c
}

func (_c *MockWalletReadModel_GetAllWalletsWithAllocations_Call) RunAndReturn(run func(ctx context.Context, officeID uuid.UUID) ([]query.Wallet, error)) *MockWalletReadModel_GetAllWalletsWithAllocations_Call {
	_c.Call.Return(run)
	return _c
}
